### ISSUE TITLE
The sample does not work with devexpress 17.2 

### ISSUE THREAD

**Issue by rajkumar82** [DevExpress-Examples/how-to-place-any-control-to-the-detail-view-e3387#1]

**Comment by rajkumar82** [comment]
The issue is GridView.cs (in dev express code) has a reference to Columnview.cs in the function below

public void SetMasterRowExpandedEx(int rowHandle, int relationIndex, bool expand)

Not sure how to fix this in the sample !

**Comment by LexEPoX** [comment]
Thank you for contacting us. We are aware of this issue and have already fixed it in version 17.2.8. Feel free to [upgrade your controls](https://documentation.devexpress.com/GeneralInformation/2221/Installation/Upgrade-Notes) to that (or a newer) version to be able to use this functionality.
